import matplotlib.pyplot as plt
fig, ax = plt.subplots()
circle = plt.circle((0,0), radius=5, color= 'blue', fill = 'false')
ax.add_patch(circle)
ax.set_xlim(-6,6)
ax.set_ylim(-6,6)
ax.set.xlabel("x-axis")
ax.set_ylabel("y-axis")
ax.set_title("circle using plt.circle()")
ax.axhline(0 , color= 'black' , linewidth = 1)
ax.axvline(0 , color= 'black' , linewidth = 1)
ax.set_aspect('equal')
plt.grid()
plt.show()